config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
  end


  resources :users
  resources :products do
    get :who_bought, on: :member
    end

    scope '(:locale)' do  
      resources :orders
      resources :line_items
      resources :carts
      root 'store#index', as: 'store_index', via: :all
    end
  end


# Depot2::Application.configure do
#   config.action_mailer.delivery_method = :smtp

#   config.action_mailer.smtp_settings = {
#     address: "smtp.gmail.com",
#     port: 587,
#     domain: "domain.of.sender.net",
#     authentication: "plain",
#     user_name: "dave",
#     password: "secret",
#     enable_starttls_auto: true
#   }
# end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #A single entry in the routing file such as
    #resources :products
  #creates SEVEN (7) different routes in your application,
  #each mapping to the Products Controller:
=begin
Http-verb path          controller/action     used-for
GET      /products      products#index        display list of all products
GET      /products/new  products#new          return an HTML form for creating a new product
POST     /products      products#create       create a product
GET      /products/:id  products#show         display a specific product
GET      /products/:id/edit products#edit     return an HTML form for editing a product
PATCH/PUT /products/:id  products#update      update a specific product
DELETE    /products/:id products#destroy      delete a specific product


When you declare your resources in routes.rb like so:
resources :products
then you automatically have the following available paths:
products_path
product_path
new_product_path
edit_product_path
  

run `rake routes` to see how it all works.
=end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Outer Heaven's Tactical Espionage Action Gallery</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>
      I18n.defaultLocale = "<%= I18n.default_locale %>";
      I18n.locale = "<%= I18n.locale %>";
    </script>
  </head>

  <body>
  <header class='main'>
    <aside>
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale',
          options_for_select(LANGUAGES, I18n.locale.to_s),
          onchange: 'this.form.submit()' %>
        <%= submit_tag 'submit', id: "submit_locale_change" %>
      <% end %>
    </aside>
    <%= image_tag 'fox_hound.jpg', alt: "High-Tech Special Forces Foxhound" %>
    <h1><%= @page_title %></h1>
    <% if @visit_counter && @visit_counter < 4 %>
    <strong>You have been to the store <%= pluralize(session[:counter], 'time', 'times') %> </strong>
    <% else %>
    <strong><%= @visit_counter %> times and you STILL haven't bought anything? What gives? </strong>
    <% end %>
  </header>
  <section class='content'>
    <nav class='side_nav'>
          <div id='cart' class='carts'>
        <%= render_if @cart && @cart.line_items.any?, @cart %>
          </div>
      <ul>
        <li><a href="/"><%= t('.home') %> </a></li>
        <li><a href="/questions"><%= t('.questions') %></a></li>
        <li><a href="/news"><%= t('.news') %></a></li>
        <li><a href="/contact"><%= t('.contact')%></a></li>
        <li>
             <aside style='color: white;'><%= Time.now.strftime("%m/%d/%Y") %></aside>
        </li>
      </ul>
      <% if session[:user_id] %>
        <nav class="logged_in_nav">
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= button_to 'Logout', logout_path, method: :delete %></li>
          </ul>
        </nav>
      <%  end %>
    </nav>

      <main class='<%= controller.controller_name%>'>
        <%= yield %>
      </main>

  </section>
  </body>
</html>